name: mobile_traffic_director
permissions:
  contents: read
'on':
  workflow_dispatch: null
concurrency:
  group: ${{ github.head_ref || github.run_id }}-github.workflow
  cancel-in-progress: true
jobs:
  cc_test:
    if: "${{\n    github.repository == 'envoyproxy/envoy'\n    && (github.event.schedule\n\
      \        || !contains(github.actor, '[bot]'))\n}}"
    name: cc_test
    permissions:
      contents: read
      packages: read
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
    - name: Checkout repository
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
    - name: Add safe directory
      run: git config --global --add safe.directory /__w/envoy/envoy
    - name: Run GcpTrafficDirectorIntegrationTest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GCP_TEST_PROJECT_PROD_API_KEY: ${{ secrets.GCP_TEST_PROJECT_PROD_API_KEY }}
        GCP_TEST_PROJECT_API_KEY: ${{ secrets.GCP_TEST_PROJECT_API_KEY }}
        ENVOY_IP_TEST_VERSIONS: v4only
      run: "cd mobile\n./bazelw run \\\n    --config=mobile-remote-ci \\\n    --config=ci\
        \ \\\n    //test/non_hermetic:gcp_traffic_director_integration_test\n"
